version: '3.8'

services:
  data-extractor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-1.0.0}
    image: data-extractor:${VERSION:-latest}
    container_name: data-extractor
    restart: unless-stopped
    
    # Environment variables
    environment:
      # Oracle Database Configuration
      - ORACLE_HOST=${ORACLE_HOST:-oracle-db}
      - ORACLE_PORT=${ORACLE_PORT:-1521}
      - ORACLE_SERVICE=${ORACLE_SERVICE:-XE}
      - ORACLE_USER=${ORACLE_USER:-testuser}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD:-testpass}
      
      # Application Configuration
      - OUTPUT_BASE_PATH=/app/data
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_WORKERS=${MAX_WORKERS:-4}
      
      # Spark Configuration
      - SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY:-2g}
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY:-2g}
      - PYSPARK_PYTHON=python3
    
    # Volume mounts
    volumes:
      # Data output directory
      - ./data:/app/data
      # Log directory
      - ./logs:/app/logs
      # Configuration files
      - ./config:/app/config:ro
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
    
    # Network settings
    networks:
      - data-extractor-net
    
    # For testing without Oracle database
    command: ["python", "-c", "print('Data Extractor Test Mode'); import time; time.sleep(3600)"]
    
    depends_on:
      - oracle-db

  # Mock Oracle Database for testing
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-test-db
    environment:
      - ORACLE_PASSWORD=testpass
      - APP_USER=testuser
      - APP_USER_PASSWORD=testpass
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./scripts/init-oracle.sql:/container-entrypoint-initdb.d/init.sql:ro
    networks:
      - data-extractor-net
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  data-extractor-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  oracle-data:
    driver: local