database:
  oracle_host: your_oracle_host
  oracle_port: 1521
  oracle_service: your_service_name
  oracle_user: your_username
  oracle_password: your_password
  output_base_path: /dbfs/data
extraction:
  max_workers: 4
  default_source: oracle_db
  use_existing_spark: true
databricks:
  cluster_mode: shared
  log_level: INFO
  output_format: parquet
  unity_catalog_volume: main/default/volume
