database:
  oracle_host: localhost
  oracle_port: 1521
  oracle_service: XE
  oracle_user: demo
  oracle_password: demo
  output_base_path: data
extraction:
  max_workers: 4
  default_source: oracle_db
